
syntax on

set showmatch
set incsearch

set fileformat=unix

filetype off
call pathogen#infect()
call pathogen#helptags()


" %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% "
"               Display of line numbers
" %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% "
 set number    "Startup: display numbers"
 nnoremap <F2> :set nonumber!<CR>:set foldcolumn=0<CR>



"  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% "
"                Indentation management                     "
"  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% "
function! SpacesAndTabs()
    if &expandtab
        retab
    else
        try
            %s/^ \+/\=substitute(submatch(0), repeat(' ', &ts), '\t', 'g')
        catch
        endtry
    endif
endfunction

nnoremap <F3> <ESC>:set expandtab!<CR>:call SpacesAndTabs()<CR><CR>

set listchars=eol:\ ,tab:\»\ ,trail:-,extends:>,precedes:<
set list

filetype plugin indent on


set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4


" docblock comments are continued when a newline is inserted
set comments=sr:/*,mb:*,ex:*/
filetype on
filetype plugin on
" check syntax with Ctrl + L
autocmd FileType php noremap &lt;C-L&gt; :!/usr/bin/env php -l %&lt;CR&gt;
autocmd FileType phtml noremap &lt;

set hlsearch

nnoremap <F9> :!pylint --rcfile=~/.pylint.rc % <CR>
nnoremap <F4> :!pep8 --max-line-length=99 % <CR>

map <leader>j :RopeGotoDefinition<CR>
map <leader>r :RopeRename<CR>

function! s:ToUppercase(str)
    % s/\(str\)/\U\1/g
endfunction

command! -nargs=1 CorrectVariable call s:ToUppercase(<f-args>)

" set statusline=
set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff},]%{fugitive#statusline()}%h%m%r%y%=%c,%l/%L\ %P
set laststatus=2

set ignorecase
