# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt autocd
unsetopt beep
bindkey -v

zstyle :compinstall filename '/home/asadones/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Load aliases
for alias_file in ~/.zsh/aliases/*; do
    source $alias_file
done

# Scripts
if [[ -n "$(ls ~/.zsh/bin)" ]]; then
    for script in ~/.zsh/bin/*; do
        eval "$($script)"
    done
fi

# Manage title
if [[ -a ~/.zsh/host_details ]]; then
    TITLE=`cat ~/.zsh/host_details`
    echo -ne "\e]1;$TITLE\a"
else
    echo -ne "\e]1;$MONSOON_PROJECT/$MONSOON_NAME\a"
fi

# Set Prompt
source ~/.zsh/prompt
